baseURL = ""
languageCode = "ru-RU"
title = "Runtu"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = [ "HTML", "RSS", "Sitemap"]

[params]
  description = "Runtu — быстрый и лёгкий Linux на русском"
  mainSections = ["post"]
  logo = 'images/logo.png'

[params.author]
  name = 'Runtu Team'
  email = 'org@runtu.org'

[params.copy]
    copy = "2007-2026 Runtu"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Скачать"
    link = "download" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.posts]
    showAuthor = false
    showDate = true
    showTags = false
    dateFormat = "02-01-2006"

[params.contact] # Contact info
    email = "org@runtu.org"
    xmpp = "runtu@conference.jabber.ru"
    phone = ""
    skype = ""
    address = ""

### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier

[privacy]
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.x]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[menu]
  [[menu.main]]
    identifier = "forum"
    name = "Форум"
    url = "https://forum.runtu.org"
    weight = 30
