baseURL = ""
languageCode = "ru-Ru"
title = "Runtu"
theme = 'terrassa'
enableRobotsTXT = true
paginate = 10
googleAnalytics = 'UA-6171888-2'

[outputs]
  home = [ "HTML", "RSS", "Sitemap"]

[author]
  name =  'Runtu Team'
  email = 'org@runtu.org'

[params]
  description = "Runtu — быстрый и лёгкий Linux на русском"
  mainSections = ["post"]
  favicon = "images/favicon.ico"
  logo = 'images/logo.png'

[params.copy]
    copy = "2007-2023 Runtu"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Скачать"
    link = "download" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.posts]
    showAuthor = false
    showDate = true
    showTags = true
    dateFormat = "01-02-2006 15:04"

[params.contact] # Contact info
    email = "org@runtu.org"
    xmpp = "runtu@conference.jabber.ru"
    phone = ""
    skype = ""
    address = ""

### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = false

[menu]
  [[menu.main]]
    identifier = "forum"
    name = "Форум"
    url = "https://forum.runtu.org"
    weight = 30
