version: '3.4'
services:
  web:
    build:
      context: .
    depends_on:
      - mysql
    volumes:
      - .:/app:cached
    command: "sh -c app/joomla.sh"
  mysql:
    image: mysql:5.6.48
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'db-data:/var/lib/mysql'
      - .:/docker-entrypoint-initdb.d
volumes:
  db-data:
